### ISSUE TITLE
Does this only work with text fields?

### ISSUE THREAD

**Issue by Ebtessam** [tameraydin/ng-inline-edit#5]
how can I use this with other input wizards?

**Comment by tameraydin** [comment]
you mean other input elements like ``textarea``? currently no, would be a nice addition though

**Comment by tameraydin** [comment]
with **0.6.0** yes; just add `inline-edit-textarea` attribute on the element.

**Comment by lakshmi1984** [comment]
Can i use it with check box and select like other Html elements?How can i Specify which html element to use?

**Comment by tameraydin** [comment]
@lakshmi1984 Nope, only text-input & textarea elements are supported:
It will be `<input type="text">` by default, and `<textarea>` if you add `inline-edit-textarea` attribute onto element.
