### ISSUE TITLE
cannot edit 0

### ISSUE THREAD

**Issue by kiddphunk** [tameraydin/ng-inline-edit#8]
I think the logic you want when constructing the text field is

'ng-if="!editMode">{{((typeof(model) !== "undefined" && model !== null)?model:placeholder)'

and not

'ng-if="!editMode">{{(model || placeholder)'

Otherwise the number 0 always evaluates to false and nothing is displayed.

**Comment by tameraydin** [comment]
Can you create a plunkr for that? I wasn't able to produce on http://tamerayd.in/ng-inline-edit/ ...

I think following part should prevent the case you're saying:

``` javascript
scope.$watch('model', function(newValue) {
  if (!isNaN(parseFloat(newValue)) && isFinite(newValue) && newValue === 0) {
    scope.model = '0';
  }
});
```

**Comment by shazzababs** [comment]
I know this is old but I had the same issue. For anyone else that encounters the problem and the above fix doesn't work. I had issues with both 0 (int) and an empty string (which would evaluate as 'false' in the original or in line 202).

Replace line 202:

'ng-if="!editMode">{{(model || placeholder)' +

with:

'ng-if="!editMode" contentEditable=true data-text="{{placeholder}}">{{model' +

and add the following css: 

[contentEditable=true]:empty:not(:focus):before{
    content:attr(data-text)
}

Great control BTW!
